name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          sudo mv allure-2.27.0/bin/allure /usr/local/bin/allure
          allure --version

      - name: Run API tests
        run: |
          cd api-tests
          mvn clean test || echo "Tests failed"
          allure generate allure-results --clean -o allure-report || echo "Allure generation failed"

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-allure-report
          path: api-tests/allure-report
