name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Install Allure CLI
        run: |
           sudo apt-get update
           sudo apt-get install -y unzip
           curl -sLo allure.zip https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
           sudo unzip -o allure.zip -d /opt/
           sudo ln -s /opt/allure-2.21.0/bin/allure /usr/bin/allure
           allure --version

      - name: Run API tests
        run: |
          cd api-tests
          mvn clean test || echo "Tests failed"
          allure generate allure-results --clean -o allure-report || echo "Allure generation failed"

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-allure-report
          path: api-tests/allure-report

      - name: List Allure results
        run: |
          ls -l api-tests/allure-results || echo "No allure-results directory"
          cat api-tests/allure-results/* || echo "No files to cat"
