name: Mobile Tests with Allure

on:
  workflow_dispatch:

jobs:
  mobile-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Appium and Allure
        run: |
          npm install -g appium
          npm install -g allure-commandline
          appium driver install uiautomator2

      - name: Set ADB install timeout for settings apk
        run: echo "APPIUM_SETTINGS_APK_INSTALL_TIMEOUT=300000" >> $GITHUB_ENV

      - name: Run tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          profile: Nexus 5
          emulator-options: -no-window -noaudio -no-boot-anim -no-snapshot-save -no-snapshot-load -memory 2048
          disable-animations: true
          cores: 2
          script: |
            set -e
            pwd
            ls -l

            nohup appium --log appium.log &
            sleep 10
            adb wait-for-device

            # Wait for emulator to fully boot (up to 3 minutes)
            timeout=180
            elapsed=0
            while [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ] && [ $elapsed -lt $timeout ]; do
              sleep 5
              elapsed=$((elapsed+5))
            done

            # Disable more system features for speed
            adb shell settings put global window_animation_scale 0.0
            adb shell settings put global transition_animation_scale 0.0
            adb shell settings put global animator_duration_scale 0.0
            adb shell settings put secure spell_checker_enabled 0

            SETTINGS_APK="/home/runner/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk"
            if [ -f "$SETTINGS_APK" ]; then
              echo "Attempting manual install of Appium settings APK"
              adb install -r "$SETTINGS_APK" || true
            else
              echo "Settings APK not found, skipping manual install"
            fi

            cd mobile-tests && mvn clean test
            TEST_EXIT_CODE=$?
            echo "Tests completed with exit code $TEST_EXIT_CODE"

            allure generate allure-results --clean -o allure-report || echo "Allure generation failed"

            echo "Killing emulator and Appium server..."
            adb -s emulator-5554 emu kill || echo "Emulator not running"
            pkill -f appium || echo "Appium not running"
            exit $TEST_EXIT_CODE

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: mobile-tests/allure-report
