name: Mobile Tests

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # workflow_dispatch:

jobs:
  mobile-tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Appium and Allure
        run: |
          npm install -g appium
          npm install -g allure-commandline
          appium driver install uiautomator2

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc

      - name: Make test script executable
        run: chmod +x .github/scripts/android-emulator-test.sh

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run mobile tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          profile: Nexus 5
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          emulator-boot-timeout: 900
          script: .github/scripts/android-emulator-test.sh

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: mobile-tests/allure-report

      - name: Upload TestNG HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-html-report
          path: mobile-tests/target/surefire-reports/*.html
