name: Mobile Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Or, for manual cache:
      # - name: Cache Maven packages
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.m2/repository
      #     key: maven-${{ runner.os }}-${{ hashFiles('mobile-tests/pom.xml') }}
      #     restore-keys: |
      #       maven-${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Appium and Allure
        run: |
          npm install -g appium
          npm install -g allure-commandline
          appium driver install uiautomator2

      - name: Set ADB install timeout
        run: echo "APPIUM_SETTINGS_APK_INSTALL_TIMEOUT=180000" >> $GITHUB_ENV

      - name: Run tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          profile: Nexus 5
          emulator-options: -no-window -noaudio -no-boot-anim
          disable-animations: true
          script: |
            nohup appium --log appium.log &
            sleep 10 && adb wait-for-device && sleep 30
            cd mobile-tests
            mvn clean test || echo "Tests failed"
            # Always attempt to generate report
            allure generate allure-results --clean -o allure-report || echo "Allure generation failed"

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: mobile-tests/allure-report