name: Playwright Tests

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        suite: [smoke]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web-tests/package-lock.json

      - name: Install dependencies
        run: |
          cd web-tests
          npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('web-tests/package-lock.json') }}

      - name: Install Playwright browsers
        run: |
          cd web-tests
          npx playwright install

      - name: Install Playwright dependencies
        if: runner.os == 'Linux'
        run: |
          cd web-tests
          npx playwright install-deps

      - name: Run ${{ matrix.suite }} tests
        run: |
          cd web-tests
          npx playwright test tests/${{ matrix.suite }}

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.os }}-${{ matrix.suite }}
          path: web-tests/playwright-report
